# Generated by Django 2.2.17 on 2021-04-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myCard', '0002_auto_20210403_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='about',
        ),
        migrations.RemoveField(
            model_name='card',
            name='media_links',
        ),
    ]
